# Copyright (C) 2022 Roberto Rossini <roberros@uio.no>
# SPDX-License-Identifier: MIT

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "call_tad_cliques/version.py"
git_describe_command = "git describe --dirty --tags --long --match v* --first-parent"