# Copyright (c) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build call-cliques Dockerfile

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-call-cliques*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/call-cliques*.Dockerfile"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/build-call-cliques*dockerfile.yml"
      - ".github/workflows/build-dockerfile.yml"
      - "containers/call-cliques*.Dockerfile"

jobs:
  build-call-cliques-dockerfile:
    name: Build call-cliques Dockerfile
    uses: robomics/call_tad_cliques/.github/workflows/build-dockerfile.yml@main
    with:
      dockerfile-glob: "containers/call-cliques*.Dockerfile"

    permissions:
      contents: read
      packages: write
